# стихи {#poetry}

## онтологически холодное стихотворение {#cold}

*в песочных часах сыплется прах умирающего времени (вариант: умирающей вечности)*

квазары карлики кометы  
сегменты времени планеты

в пустых глазницах вечности  
нет места человечности

под радиопульсаров хор  
сгораю будто метеор

из праха плёнка были  
а я из звёздной пыли

## безымянное {#unnamed}

_намеренно без названия, потому что назвать -- значит ограничить, а этого как раз хотелось бы избежать_

давайте присядем на мягкую Вечность  
и будем следить за тем,  
как устремляются в бесконечность  
духи нескучных тем

для разговоров (читать -- болтовни).  
смотрите, как быстро убегают они!

давайте следить за Пространства игрою  
за суетой Времён,  
за сутью вещей, которым, порою  
ещё не дали имён.

и вряд ли дадут. давайте встрепещем  
от вещи, большей понятия «вещи»!

## мы тоже {#we_too}

о Боже!  
мы это знание выдумывали тоже.  
мы эту правду чувствовали тоже.  
мы тоже.

## малітва {#pray}

штосьці губляем, штосьці знаходзім,  
сонца свеціць лампай стоватнай.  
божа, калі ты існуеш у прыродзе,  
зрабі  
мяне  
адэкватным!

свой квіток я згубіў на ўваходзе.  
ну і чорт з ім, так пройдзем.

## эхо перезвона колокольчиков {#echo}

...и ей казалось. что внутри  
всё не такое, как снаружи  
что вот -- часы пробили три  
и вот -- пора готовить ужин

и небо, только посмотри  
бывает и в ближайшей луже  
и что оно, держу пари,  
ничем обычного не хуже

что в отраженьи сточных вод  
есть свой, особый небосвод

что поток мыслей в голове  
бывает шире или уже  
и что несчастный человек  
придумал пистолет и ружья

а счастье -- это так легко,  
но счастлив только тот, кто нужен  
кто может жить не беспоко  
я, не надоев и не нарушив

и что махнуть бы навсегда  
в Сеул,  
Бангкок,  
а может --  
в Дели

а путеводная звезда  
сама найдёт  
любое «где я?»

## паэзія -- гэта ахвяра і подзвіг {#poetry_by}

паэзія -- гэта ахвяра і подзвіг  
дзякуй Богу, што тое, што я пішу - не паэзія,  
а так, звычайны душэўны эксгібіцыянізм.  
паэзія -- гэта як лёгкі подых,  
ці амерыканскія горкі, што хутка нясуць цябе ўніз.

паэзія -- гэта голая манашка з наколкай на спіне,  
ці маўклівы інтэлігент, якога замучыў штодзённы быт.  
удзень ён жыве ў рытме разам з усімі,  
каб ноччу прачнуцца -- у халодным поце -- злавіўшы свой рытм.

паэзія ніколі не церпіць халтуры  
ці фальшу, стракатасці ў вонкавасці.  
глыбіня для яе -- другая натура,  
і гэтых натураў -- бясконцасць.

паэзія -- гэта няспынныя гонкі,  
у якіх ты ніколі не прыйдзеш да фінішу  
яна ўнутры, хоць ўвесь час лезе вонкі.  
шэпт ветру,  
пах яблыкаў,  
плыні шум.

__P.S.__ раптам падхоплены плынню са словаў  
ты можаш выказаць невыказнае  
будзь па-за шаблёнамі, па-за ўмовамі  
заўсёды тут і заўсёды па-за.

## некоторые из ритмов (сны с ны) {#rhytms}

### ритм первый {#rhytms_1}

сегодня мы смотрели с ны  
на яблоневый сад,  
на смену ритма тишины  
один раз в два часа,

на бездну звёзд, которых нет,  
крупицу всех, что есть,  
в пространстве-времени просвет,  
куда нам не пролезть.

### ритм второй {#rhytms_2}

сегодня мы смотрели с ны  
на то, как умирают  
смы  
слы. и то, к  
ак снова возникают

такое чувство, будто ток  
ом бьёт,  
и жжёт как йод.

пустоты дуккха заполняет,  
пчела бессмертная поёт.

## опыт общения с известным профессиональным литератором (по мотивам Шекли) {#experience}

-- Лимля, печукрудалия, дадалка, псевдоангелы какие-то под псевдонимбами и, как его, гладкошёрстный пурктик? -- говорит мне один известный профессиональный литератор, протирая стёклочки

-- Не марайте бумагу, займитесь делом  
Всё высосано из пальца

_Чешуя его из жёлтой становится белой_  
_И он втягивает свою голову в панцирь._

## кредо (2010) {#credo}

Божа, я хачу глядзець людзям у вочы  
не сармеючыся. і не імкнучыся адвесці позірк  
я хачу адчуваць кожнай клеткай свайго цела  
жыццё. яго пульс і подых  
я хачу наперад крочыць  
з адчуваннем, што ўсё зрабіў правільна.  
а яшчэ -- каб уласныя адчуванні  
ніколі мяне не падманвалі

я хачу -- з захаваннем аўтарскай інтанацыі, арфаграфіі і пунктуацыі  
я хачу ўсё па пунктах, заснавальна, ці адразу, імправізацыяй

я хачу, каб галоўным словам стала «дзякуй», а галоўным пачуццем -- любоў  
я хачу гаварыць адразу, без уводных прамоў  
я хачу, каб любая параза была найменш значнай з падзей  
і, нарэшце, паверыць у людзей

я хачу быць камусьці патрэбным  
я хачу ў вечар суботы  
я хачу хацець не дарэмна  
я хачу адчування палёту  
я хачу сабе крылы  
і яшчэ дачакаць, калі яно прыйдзе, доўгачаканае «потым»

я хачу, каб усё было шчыра  
амінь

## один мой день {#one_my_day}

норковые шубы вылезли из нор

дамы идут в  
[schub](https://psychiatry.academic.ru/3005/%D0%A8%D1%83%D0%B1_%D1%88%D0%B8%D0%B7%D0%BE%D1%84%D1%80%D0%B5%D0%BD%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9)\'ах  
вне возможных норм

идут пускаясь в пляску на облокаблуках  
мужья ведут коляски на длинных поводках

летят часы с кукушкой разносят жизнесроки  
а дзенские хлопушки пускают дхарм потоки

разбужена округа хлопками дзен-петард  
чаи "беседа" (с другом) в капсулах ретард

-- пролонг-реализация потребности в общении  
для чайных корпораций же - путь к обогащению

_...а лебеди в балетках ныряют в водоём_  
_ну всё, настал таблеток торжественный приём_

## ещё один день {#one_more_day}

ещё один день. его Мера и Суть -- Всё Поглотивший Испуг  
уйди, нечистый. забери с собой свои

- Обоняние
- Зрение
- Слух

ещё один день. его мера -- испуг и отчаяние  
уйди нечистый. забери с собой свои

- Зрение
- Слух
- Обоняние

в общем-то, вот они, опрелые прелести жизни в долг  
согласился бы и на кондицию как у Кандинского, вот только и к ней путь долог  
путь долог, а движения нет. нет движения кро ме движения кро ви  
радует только что хоть что третий из органов зрения не обезбровлен

поиск решения гол, он сам по себе, с него спала иллюзия смысла  
муха сознания (какая там бабочка!) вязнет в меду из мыслей  
который почему-то льётся непрерывным потопом  
манит самая суть? попробуй добраться до неё автостопом!

## ночь {#night}

ночь -- это время долгожданной свободы  
ото всех не тобой обусловленных  
условностей  
мысли в голове прокручиваются с безумной скоростью  
и исчезают, унося от тебя собой дневные заботы

ночью нет места для правил и обязательств  
безумно длинна, но это ей даже идёт  
стечение
вялотекущести  
обстоятельств  
и иллюзорности грёз, где выход не там же, где вход

в ночные часы я кажусь себе немножечко лучше  
видя лишь то, что всё время старался увидеть  
повергая  
Всесильный  
Его Величество Случай  
и возлюбя  
то, что хотел ненавидеть

ночью нет рамок, ночью стёрты границы  
бессмысленен смысл, отныне смысл -- ты сам  
ты волен лететь навеки свободною птицей  
в мире, податливом, как мягкий кусок бабль-гам

## 100+1 Шлях Адчуць Сябе Поўным Лузерам, Робячы ўсё Правільна (рэп на дзень народзінаў) {#rap}

_красавік 2010_

я ніяк не магу пазбавіцца ад адчування таго, што буду жыць вечна  
гэтае адчуванне засела ў мяне ў самых глыбінях свядомасці, і яго не  
вытравіш адтуль нават дыхлафосам  
словы бываюць бессэнсоўнымі (калі прыходзіцца казаць і казаць нешта, толькі каб яны адчапіліся),  
і я, часам, паводжу сябе ну вельмі недарэчна --  
але ўсё роўна, лепей так, чым вечна хадзіць з высока задраным носам.

я ніколі не веру ў сваю правату, калі мне кажуць: «хлопча, ты маеш рацыю!»  
і гатовы на ўсё, каб яе даказаць, калі з мяне ўсе смяюцца.  
я імкнуся не губляць твара, праяўляць велікадушша, усміхацца й смяяцца.  
а потым б'юся аб сценку і думаю: «калі яны ўсе заб'юцца!»

я прывык фіксаваць свядомасць на адным чалавеку ці справе  
што зробіш, галава ўвесь час занятая клопатам аб клопатах, тваіх і сваіх  
(канешне, толькі тады, калі яна свабодная ад думак аб пазачарговай  
страве -- у такія моманты звычайна зусім не да іх...)

я прывык увесь час вітаць у аблоках, вандруючы ад мары да новай мары,  
ісці па шляху, што мне асабіста выдзеліў Бог  
у цемры настолькі глыбокай, што хоць выкалі вока,  
сярод мной жа настаўленых абставін і нейкіх там планаў  
спатыкнуўшыся й мацюгнуўшыся, упаўшы ў лужыну (чамусьці заўсёды тварам),  
устаць і пайсці, не заўважаючы, што ідзеш у іншы бок.

## трасянка {#trasianka}

таки ужо чалавек, яго судьба --  
мы надзяваем урэменные маски  
наги тым часам дзве, и лыжа тожа два  
скальзяць па снегу и траве (але са змазкай)

яшчэ у чалавека дзве руки,  
два вухи, дзве наздры и сам ён парны  
и дзве наги, и два чаравики,  
па усёй сваёй прыродзе ён бинарны

там дзе ёсць крышка, заусёды ёсць и дно,  
а на гениальна знойдзецца бяздарна  
у дваякасци такой жыццё. адно.

не прапусци. не карыстайся марна

## числовая поэзия {#numbers}

### геометрическое стихотворение со знаменателем одна вторая {#numbers_1}

один *(читается за одну секунду)*  
одна вторая *(читается за одну вторую секунды)*  
одна четвёртая *(читается за одну четвёртую секунды)*  
одна восьмая *(читается за одну восьмую секунды)*  
одна шестнадцатая *(читается за одну шестнадцатую секунды)*  
_<...>_

_число строк в стихотворении бесконечное (счётное)._  
_полностью стихотворение читается за две секунды._

### обобщённое гармоническое стихотворение (стихотворение Дирихле) с параметром, равным двум {#numbers_2}

один *(читается за одну секунду)*  
одна четвёртая *(читается за одну четвёртую секунды)*  
одна девятая *(читается за одну девятую секунды)*  
одна шестнадцатая *(читается за одну шестнадцатую секунды)*  
одна двадцать пятая *(читается за одну двадцать пятую секунды)*  
_<...>_  

_число строк в стихотворении бесконечное (счётное)._  
_полностью стихотворение читается за $\frac{\pi^2}{6}$ секунд._

## в честь пятидесятого найденного числа Мерсенна {#mersen}

$x_0=$ очередной поток дхарм пытающийся скрыться в миражах и за ярлыками  
$x_1=$ клякса на чистом листе попытки начать всё сначала  
$x_2=$ то, как она просачивается сквозь простыню на ткань пространства и времени  
$\cdots$

-- глубоко извращённый секс со многими неизвестными одно из которых -- ты

и даже учтя что не каждый переживёт встречу с сутью  
стоит учитывать что для некоторых она --  
едва ли не самое простое испытание  
в их жизни

$1, 3, 7, 15, 31, 63, 127, 255, \cdots, 2 ^{77232917} - 1, \cdots$  
как забавно, что порой чуть ли не самые простые вещи  
приходится искать так долго

и что самой лучшей структурой  
вдруг может разродиться сам хаос  
смеясь над твоими бесплодными поисками

## на смерть семантики {#semantics}

хамелеоньи грибницы чисты  
густы фараонов гробницы  
смысл утерян. огни Пустоты --  
новой семантики лица

## парадоксов рукав {#paradox}

парадоксов рукав,  
где пространство --  
ручной колонтитул.

истончается быль  
и семантики порвана ткань.

тяжек крест, словно орден.  
удар приговора --  
как титул.

смерть --  
как главная тема,  
лейтмотив.

жизнь --  
немого гортань.

## оригинальность многослойных смыслов {#original}

_посвящается мезолимбическому дофаминовому пути_

весь мир мультяшен и ненастоящ  
орлиной солью высыпан паркет  
лишь голос Голосовкера звенящ  
он громко зазывает на банкет

где робкий одинокий мыслепут  
в который раз распутывает след  
загадочный: сейчас он, вроде, тут  
а через миг -- уже, похоже, нет

этаж затих. на сестринском посту  
звучит раскатом братская молитва.  
бассейн наплакан. гладко выбрит стул  
он храбр, и оттого -- опасной бритвой.

в созвездии Большой Столовой Ножки  
корабль наконец-то лёг на курс.  
хоть странен порождённый мной дискурс  
в контексте мирозданья многоножки.

как рёв сирен, когда я заземлился  
как вой вселен  
ных, что снуют без дела

как саблезубость Нельсона Манделы  
витиеватость позабытых истин  
и смысл, что как будто испарился

## ортогональность позитронных смыслов {#orthogonality}

нож -- это бремя жданодолгой свободы  
ото всех не тобой  
гиппопанк звучит в каждом доме уже практически годы

контексты мирозданья многоножки  
разорваны, как овощи в окрошке

предвещая беды, бады, Будды и боды  
предвещая кораллы и хороводы

так скажи Архи тектор  
правда ли те кто?

предвещая великий отбой

_не барайте марагу, печукрудаля темя:_  
_у вас голова испанца._  
_ползяк, червоточащий семя_  
_несёт однородность субстанции_

## белое стихотворение про схизис {#shizis}

_**Сцена:** универсум психики._  
_**Крупный план:** зрители видят надлом._  
_Из надлома выкатывается яблоко._

Помидор грызёт Яблоко  
Яблоко грызёт Слива  
Сливу грызёт Ближайший  
Ближайшего никто не грызёт

_Примечание:_ **яблоки** -- это такие блоки, из которых состоит человеческое «я».

## песнопения хора норковых schub {#choir}

слышите выжжена вышита выше там  
в крыше ли в трубке дыра  
в общем-то именно так  
выглядит наша нора

вокруг ползла пересечённая оазис:  
мать,  
мадемуазель,  
Империя!
