# проза {#prose}

## аниил дхармс. случа(йные наброск)и {#dharmes}

**об авторе:** *буддист-абсурдист.*

проблема -- это концепция проблемы. убрать уровень концепций -- значит убрать уровень проблем. это как в прятки играть: чтобы тебя не смогли найти, нужно закрыть глаза. дети интуитивно догадываются, что нужно всё делать именно так, но получается у них далеко не всегда. просто они забывают закрыть третий глаз. далее третий глаз поворачивается внутрь головы и пристально рассматривает носителя. рассматривает до тех пор, пока не станет понятно, что носителя-то и нет! а как его после такого найдёшь?

у Будды был один ученик, испытывавший к нему большую привязанность (и выражавший её тем, что постоянно пытался привлечь внимание Учителя разговорами). Будда давно повторял, что привязанность -- причина страданий, и он совсем не хотел страданий ученика, поэтому часто спрашивал у него: чего ты ко мне привязался?!

Окончательную Истину невозможно увидеть ни одним из трёх своих глаз. ими можно увидеть лишь то, что увидеть её с их помощью нельзя. и увидев это, можно увидеть Окончательную Истину. но не глазами, это сложно объяснить... вы попробуйте, сами увидите.

## наш муравейник: следом за Моруа {#morua}

Ардагони был ещё совсем молодым божеством. Мать в первый раз привела его выбрать себе игрушечный мирок -- сущий пустяк по сравнению с теми, которыми ворочали взрослые! - в магазин игрушек. Населявшие этот мир народы были такими примитивными, а сам он -- так прост в обращении, что его без опаски можно было доверить и ребёнку.

Внутри пластиковой колбы на пластиковой подставке висела крохотная планетка. Всё, что требовалось от владельца -- это раз в месяц подбрасывать туда щепотку любви и несколько капелек счастья, реализуя свою божественную природу.

Ардагони исправно делал всё это, пока не вырос и не занялся делами серьёзнее и величественнее, позабыв свои детские игрушки. А люди, которые населяли этот мир, тем временем продолжали жить свои жизни, счастья и любви в которых становилось всё меньше. При этом почему-то они всерьёз считали, что счастливыми им мешают быть другие люди (увы, ума многим из них тоже недоставало) и вели свои бесконечные скучные войны.

Хотя нет, бесконечными они как раз не были: в конце концов жителей на планее осталось совсем мало, да и оставшиеся после всех этих химических атак и ядерных бомб особым здоровьем не отличались. Если у кого-то и рождались дети, они были уродами и быстро умирали. В конце концов на всей планете осталось только двое: Альманора и Финкьяри.

Этот мир ещё долго никто не доставал из мешка для старых игрушек, так что никто так и не увидел, как он доживал свои последние дни. И как умер Финкьяри, изо всех сил пытаясь сберечь последние крохи любви (крохи для этого мира, но не для него самого!) для Альманоры, своей Королевы.

## трагические судьбы гадких утят {#ducks}

Жил-был один гадкий утёнок. Ну, по правде говоря, никаким утёнком он не был, да и гадким был уж точно куда меньше остальных, но о том, что он гадкий и о том, что он утёнок, ему постоянно твердили окружающие, и оснований для сомнения наш герой не видел. Да что там говорить, он и близко не мог допустить даже мысли о том, что этот порядок вещей неправильный и не догадывался о своей сути: огромном потенциале прекрасного лебедя. Не догадывался и так никогда не догадался, ровно как и не догадались окружающие: "утёнка" успели сломать раньше, чем он присоединился к остальным лебедям. Так что наш утёнок попал в дурку, где и провёл остаток своей полной боли жизни в овощном состоянии, напичканный нейролептиками первого поколения -- современные препараты утки-врачи признавать отказывались.

Другому же утёнку повезло больше: он успел превратиться в лебедя до того, как случилась катастрофа, но крышей всё равно поехал. Остаток жизни его мучали кошмары и воспоминания о прошлом, и свою прекрасно-лебединую жизнь он прожил, сидя на препаратах и борясь с обострениями.

А ещё один утёнок был в курсе оригинальной истории про гадкого утёнка и тоже любил лебедей. Он уже был готов к преображению в прекрасного лебедя, вот только оказалось, что не лебедь он никакой, а реально гадкий утёнок с мегаломанией. В дурку его отправили уже сами лебеди: многие из них в душе оказались не такими уж и прекрасными, а заносчивыми лебедями-снобами, презирающими чужаков. И они совсем не любили, когда к ним примазывались всякие untervogel.

## стул в небытие {#nihility}

**вначале не было ничего.**

нет, действительно, в свежесамозародившейся Вселенной для «ничего» просто не хватало места: вся она полнилась неисчислимым множеством сущностей, слишком свободных и мало с чем определившихся, чтобы иметь достаточно уловимые, хоть как-то пригодные для их описания, свойства.

эти сущности кружились в поначалу неупорядоченном танце, притягиваясь друг к другу и отталкиваясь: они провели так не одну вечность, совершенно, даже не пытайтесь, несоизмеримое со временем до их (за)рождения, время.

но и это было не навсегда: взаимодействие порождало первые локальные области упорядоченности и первые структуры -- слишком нестабильные, чтобы существовать вечно, но каждая такая нестабильность была шажком вперёд, пусть и не всегда удачным. время от времени начали появляляться структуры, которые хоть и не могли избежать разрушения, но были уже достаточно живучими, чтобы просуществовать и развиваться в течение заметных периодов времени.

**сложно перечислить всё, что было создано в этом танце роя сущностей, но самым удачным его изобретением стал Хранитель.**

Хранитель был, по сути, чем-то вроде божества, создающего, упорядочивающего и постоянно ремонтирующего постоянно разрушающийся мир. Описания того, как Хранитель (за)родился, как он начал осознавать себя, мир вокруг и свои возможности, по сути, рассказа про детство божества и его внутренний мир, порождающий внешний, хватило бы на целую (глубоко сакральную) книгу, но он не был тщеславен и не собирался писать мемуаров и автобиографий.

мир был невелик, а населяющие его существа -- прекрасны. Хранитель любил их всей душой, но при всей своей любви уберечь этот мир полностью не было под силу даже ему, и некоторые любимые им структуры, в том числе и существа, всё равно разрушались.

периферия мира была упорядочена (пусть и с локальными возмущениями беспорядка), в центре же мира бурлил хаос -- именно там зарождались новые структуры и именно там могла погибнуть неосторожная старая.

за периферией же начиналось детерминирование и остановка всего, полный порядок, а за полным порядком шло небытие, как его ещё наиболее экстремальное воплощение. небытие не оставляло попыток наступления и поглощения мира -- Хранитель же сдерживал его во время таких интервенций.

когда же небытие было спокойно, Хранитель, время от времени, сидел на стуле скраю мира и молча наблюдал за этой вечной пустотой -- только так он мог сполна чувствовать вверенный ему мир. никто не знал, что он думал в эти моменты, и он мог считать своим успехом, что никто из так нежно любимых им созданий не был знаком со всеми этими чертовски тяжёлыми вещами.

**Никто из них не мог понять его выражения лица после всех этих молчаливых медитаций, увидев в глазах Хранителя весь ужас подступающей к их миру, вечно стремящейся на него наброситься, Неизбежности.**

## миры как касеты и грамофонные пластинки {#worlds}

*невечное возвращение.*

Описать мир каких-высших существ, которые записывают Вселенные вроде нашей на аналоги грамопластинок и аудиокассет, тиражируют и продают. В итоге такое существо может раз за разом пережить всё существование Вселенной целиком, от начала до конца, со всеми переживаниями всех её обитателей и наблюдая за местами, где ни разу не побывало ни одно живое существо. Населения миров оживают раз за разом и раз за разом умирают, причём на бессчисленом количестве экземпляров записи. Кто-то собирает целые коллекции Вселенных, которые пылятся на полках и проигрываются изредка, а то и вообще никогда.

Описать, как плеер зажёвывает и портит кассету прямо посреди драматичной истории, происходящей с её обитателями (история описывается параллельно с повествованием об этих высших существах, причём имена эта история и кажется основной по построению текста). Кассету выбрасывают в мусорку.

## драматурги {#drama}

Драматурги -- сверхъестественные существа, вмешивающиеся в (ранее благополучные) судьбы существ или целых миров, чтобы сделать из них цепляющую за живое эмоционально насыщенную либо просто поучительную историю, призванную удовлетворить их и Наблюдателей либо стать учебными пособиями для других надмировых существ.

При этом они могут в каком-то смысле любить своих жертв/персонажей, как своих персонажей может любить писатель, позже их убивающий. и как раз тем, кого они любят больше всего, кто наиболее значим в Повествовании, они и создают наиболее серьёзные испытания.

### читатели {#readers}

Читатели -- большие любители историй. Они читают истории миров, которые пишут народы и цивилизации, и уже от авторов зависит, бросят ли их мир, не дочитав историю даже до середины, или будут перечитывать вновь и вновь, обеспечив миру ницшеанское вечное возвращение (аналог жизни после смерти, но в масштабах целого мира).

## инструменты {#instruments}

Может ли у инструмента быть своё, независимое (и ложное) мнение о том. что с его помощью делают? Что он думает о своём создателе? Что он думает о том, кто им пользуется? Как он оценивает важность своей роли в мироздании?

Считает ли линейка себя мерой всех вещей, а молот кузнеца -- ковцом своей судьбы? Каких взглядов придерживается молоток, а каких -- отвёртка?

Рады ли они своему (пред)назначению и как относятся к создателю и пользователю, если существование приносит им в основном боль? Если их роль в мироздании при этом велика? Если ничтожна?

Смысл в том, что мы сами можем быть инструментами, которыми пользуются другие люди и высшие силы. И мы часто не знаем своей подлинной роли: какая разница, что мы там мы о себе думаем?

## пустыня {#desert}

_суровое наказание высших сил: я заключён в звуке, разносящемся над пустыней._

что это за звук, я не знаю, да и некому знать: здесь есть только я. у него нету слушателя, нет у него и источника. кроме того, пустыня бескрайняя: если бы здесь и был кто-то, то куда бы он ни пошёл, он шёл бы вечно. но здесь никого нет, поэтому идти некому и некуда.

моя темница звучит не так уж и долго и быстро замолкает. перед ней была вечность небытия и пустоты, они же ожидают меня и после.

а потом всё повторяется: та же пустыня, та же темница и те же мысли.

каждое движение сознания, каждое мгновение моего существования уже было несчётное количество раз и будет столько же.

а я даже не знаю, со мной ли.

## город и числа {#town}

город покрыт домами. город находится в сетях маршрутов общественного транспорта. город оснащён, город снабжён многими другими пронумерованными объектами, процессами и явлениями.

числа делят город на зоны влияния: так, маршрут двадцать девятого троллейбуса -- это зона влияния числа 29.

люди же живут примерно в одних и тех же домах. встают примерно в одно и то же время. едут примерно на одних и тех же маршрутах, успевая или опаздывая на работу примерно с одинаковой частотой.

однако время от времени картина меняются: люди меняют номера домов, меняют график работы, меняют сами работы вместе с номерами зданий, в которых те находятся... кроме этого, судя по тому, насколько активно они этим занимаются, люди очень любят рождаться и умирать, приобретая номера в книгах учёта рождения и смертей.

_так числа обретают динамику._

люди связывают с числами какие-то значения, эмоции, надежды и страхи.

вокруг каждого числа формируется целый ореол кусочков человеческих личностей (некоторые из которых могли уже и погибнуть), целый ореол значений: снова-таки динамичные. и на некотором абстрактном уровне, с одной стороны, созданном городом и людьми, а с другой -- освобождённом от них абстрагированием, эти числа оживают.

и на этом уровне числа живут своей жизнью, вступают в отношения: дружат, любят, плетут интриги и дерутся за сферы влияния. и подчиняются законам, например, предельным теоремам теории вероятностей.

_но может ли число быть незаконопослушным?_

## бритва Оккама {#occam}

помимо основной сюжетной линии по ходу повествования вводится много «лишних» персонажей и бессмысленных ни к чему не приводящих линий. множество "висящих на сцене ружей", которые и не собирались выстреливать.

а ещё по сюжету орудует какой-то серийный убийца по кличке Оккам, убивающий своих жертв бритвой. и ближе к концу никого из лишних персонажей не остаётся, остаётся только основная сюжетная линия, приходящая к развязке.

## цена чудес {#miracles}

В центре повествования - прибор, который позволяет подкрутить вероятность какого-то события (в том числе превратить крайне маловероятные события в происходящие "почти наверное", по сути превращая обладателя в чудотворца).

Но у этих чудес есть цена (побочный эффект) -- во время подобных стохастических вмешательств могут измениться и вероятности зависимых событий, в том числе и совсем неприятных для обладателя и маловероятных до применения прибора.

## на руинах микрокосма (руины разума) {#ruines}

в будущем появляется технология, позволяющая ненадолго проникнуть в разрушающийся мозг умершего человека, в некоторой степени «оживить» его на время.

умирает профессор, инженер либо ещё какой-то человек, остающийся единственным носителем знаний по какому-то жизненно важному для других вопросу (будет называть его профессор). он прожил много столетий, и его тело -- тело глубокого старика. люди, которые путешествуют по его сознанию встречаются с его личностями в разные периоды: ребёнок, подросток, студент и так далее.

сначала воспоминания оживают, а потом начинают разрушаться: иссыхают водоёмы, сохнут растения, ветшают здания. в конце концов путешествующие встречаются с самой поздней личностью и узнают то, что хотели. профессор в это время преображается и снова становится молодым, какие-то вещи ему всё же подконтрольны.

последняя сцена -- профессор (или кто там) ложится на траву вместе со своей давно умершей любовью, ожившей в этом воспоминании, и они вместе наблюдают, как гаснут звёзды. на заднем плане в это время рушатся здания.

## бессмертие по Корсакову {#immortal}

история про добровольца, участвовавшего в экспериментах по продлению жизни и ставшего биологически бессмертным. со временем у него развился корсаковский синдром (помнит прошлое до какого-то момента, а вот способность запоминать текущие события существенно нарушена), что не так уж неожиданно, потому что на очень длительные периоды времени человеческой памяти не хватит.

начинается история с того, что герой остаётся единственным выжившим на Земле. память о том, что происходило начиная с какого-то момента (объявления о каком-то крупном физическом эксперименте, в результате и погубившим людей), очень туманная, а свои старые записи он найти не может.

он начинает вести новый дневник, пытаясь понять, что произошло, собрав паззл воспоминаний. время от времени его отбрасывают назад проблемы с памятью, и он заново перечитывает вещи, которые писал совсем недавно. в конце концов у него складывается чёткая картина того, что случилось с человечеством.

однако заканчивается всё тем, что он снова всё забывает, и начинает поиск сначала: становится ясно, что он заново переоткрывал для себя историю гибели человечества уже много раз.

## распределённое бессмертие и личностная диффузия {#distributed}

диффузное общение -- общение, состоящее во взаимном обмене идеями, взаимном обогащении ими. может затухать (временно или навсегда) при взаимном насыщении. если обмен идёт в одну сторону, общение называется осмотическим.

интересно было бы вообразить сообщество существ, общение которых доходило бы до полного взаимного построения моделей личности друг друга (всеохватывающая theory of mind). у них бы не было техники, мобильной связи, зато у каждого существа была бы не только индивидуальность, но и коллективный опыт остальных.

если одному существу нужно обдумать проблему -- оно может посоветоваться с образом другого у себя в голове. при встрече двух разных существ образы в головах синхронизируются, дополняются (если эти образы модифицируются в их головах, нужен механизм разрешения конфликтов. иначе просто инкрементное обновление до последней возможной версии). приводить аналогии с VCS и системами резервного копирования. если первоначальный носитель личности погибает, личность можно восстановить из распределённо хранимого бэкапа в специальный сосуд, в который вливается наиболее современная и полная её версия.

неплохая завязка: группа этих существ каким-то образом оказывается разделена на две подгруппы, так что никакая связь невозможна. каждая восстанавливает недостающие личности из "бэкапов" на своей стороне. в итоге получается две альтернативные ветви развития одних и тех же личностей. что произойдёт, когда они встретятся?

## веган на планете хищных растений {#vegan}

космический корабль вегана-исследователя терпит крушение на планете, покрытой хищными растениями. он ждёт спасательную миссию и пытается выжить там любой ценой. маскируется, прячется, охотится на них сам, они охотятся на него.

сначала у него есть бластер. сцены, где он выжигает хищные растения бластером, могут быть крутыми. потом бластер ломается, и дерётся он уже ножом.

писать нужно с максимальной концентрацией штампов НФ, американскими именами и получить в итоге пародию на космические боевики.