# бестиарий {#beastie}

_вымышленные существа._

**Озирости** -- существо, для обслуживания которого создан наш мир. Оно питается обманутыми ожиданиями, прошедшими любвями, разачарованиями и прочим. Любовь, вдохновение, красота, утопии, мечты о лучшей жизни существуют лишь для того, чтобы быть в какой-то момент поломанными и пойти Озирости на корм. Самое вкусное блюдо для него -- уничтожение любимого объекта (в обобщённом смысле) сильного и благородного человека, готового отдать свою жизнь, чтобы свою любовь (в обобщённом смысле) защитить.

**Вселенский Пастух, его Альдебараны, первичные бульоны, приготовленные из звёздной пыли, галактика как мясорубка и круговорот веществ в природе как мясорубка.**

**Большой взрыд** -- одна из малоизвестных космологических теорий. Состоит в том, что новые Вселенные постоянно выплакивает **Сонали**, почти забытое божество из почти забытого пантеона. **Сонали** редко плачет, но когда она плачет, она выплакивает целые Вселенные.

**мыслепуты** -- существа, запутывающие мысли.

**призраки** -- ностальгия Вселенной по исчезнувшему объекту, её воспоминание о нём. аналогия такая: мы могли испытывать какое-то сильное чувство, например любовь, к кому-то или чему-то. само это чувство ушло, но вспоминая о нём, мы можем чувствовать ностальгию по этому чувству, и в каком-то неполном виде оно снова оживает. так и призраки -- это ожившие воспоминания в сознании Вселенной.

**Мнох** -- Порождающий Метачитатель.

**Шибайоми** -- Начало. Ломка. Перестройка. Значение. Событие. Ненависть этого мира, его гнев и боль.

**Абаломпе** -- хранитель Структуры, Формы, управляющий Метаморфозами, Деформациями, Преобразованиями. Весь Порядок (и, следовательно, вся несвобода) -- его сфера и ответственность. Он -- персонификация всей математики и химии нашего мира, а также большей части искусства, кроме бесформенного -- ташизма, например.

**Юироа** -- мать Невозможного, богиня парадоксов. Реализовывалась через Эшера, Бертрана Рассела и многих других.

**Ильсанори** -- это Пространство и это Время.

**Безымянная** -- хранительница Бесформенного, Невыразимого, мать едва намеченного, туманного. Отвечает за непонимание и интуицию, и бесформенное искусство -- уже её сфера.

**Исиндала** -- богиня Абстракции. Редко покидает Платоновский мир идей. Покровительница всех шизоидов.

**Шибайоми** -- Начало, Поломка, Перестройка, Значение, Событие. Ненависть мира, его гнев и боль.

**Миртазоба, Ардагони, Имитах, Шмиаоа, Эмолииивоца, Силиали, Исингера, Вольцемаг, Истания, Истарга, Иртасан, Ирмитья, Ирнасика, Фиртаканья, Финкьяри, Фиртаканья, Толкунак, Ильнаси, Альманора, Арьяти, Арсабха, Артабола, Ардагони, Ирнабоя, Ирданья, Ингабека, Саламутья, Сыятфе, Липёта** -- пока что не додуманные существа.