# полусонные фразочки {#phrases}

- в автобусе работаю, в троллейбусе отдыхаю

- весь устный веб я перевираю

- изнутри знает, что язык изменённый

- ключ оставил с войн

- лежит в передаче лесу углеводов

- людей, которые переводят свою жизнь в последний монолог

- молодой человек заземлился

- наша родная голова разъезжается

- однажды в обычную пятку войны влетело-вылетело

- озеро -- обман. Вселился в селюху и подумал, что я галлюцинирую

- она начинание, сразу не предвидел. но она не начало

- Пётр встал вопреки, опрокинув руки скрипкой (привокзальные крюки согласованы с улыбкой)

- по всем девятым каналам девяносто пятого года

- пожары двадцатилетнего возраста

- предложение плёнки

- семья, которая была расплавленным сыром

- с невероятной скоростью, которой осталось двадцать минут

- средняя страница -- девять девять десять

- так я думаю в течение недель, а так -- только с вами

- тебе дали новый мир, который Сталин повышал первой партией

- что толку было изобретать три измерения, если я постоянно застреваю в пикселях? это как про время у кого-то из фашистов.

- этот сказочно богатый плакат не принёс нам никаких событий

- я ведь говорил тебе не верить в то что может ему навредить

- над искривым огнём бежать и струиться счастливо в нём

- относительно пустынной точки пересечённую точку

- он крадётся беспилотным цветом

- купи своей девушке латы без очереди и переплаты

- всякий "всё есть" (all inclusive) мнит себя лидером, когда это просто игра

- частично признался, потом свою вину запретил, на несколько дней или даже два месяца

- запутался в составе: ложка капель или ложка воды

- да она носу китайца мечта насекомого рот!

- эти воды лекарства были вредными? тогда очистить всё вместе.

- кетчуп-пароли, кетчуп-пароли: губки играют новые роли, буквы играют новые роли

- Большая Голова содержит возвращение

- Как там у тебя с девчонками, с семьёй, с молитвами?

- ринуться\^ в пятнадцатой.

- &:водяная(хм) роскошь™ измочалена(да ну!) до(а как без этого?)
  блеска #(орёл не всегда тот, за кого себя выдаёт)

- ;мо ?тле::разобрать::ниеь ом

- стр..кт..ра б..зум..я

- &((берего вой) линейзадолжать)?

- ;те ли существа  
  хотедавайте будем честными :---: наверное главное впечатление за сегоаря  
  !бездонность как 1порядок из самых замеча_АРХИТЕКТУРА_тельных свойств

  в этой **(бесс)мысленной кашице** хранится примерно **8/9 сути вещей**, остальное завтра

  1. знать меня совсем надёжней, чем .ПОДОБИЕ. в сети (знать меня совсем обычней)
  2. знать меня совсем (ты совсем меня знаешь)  
    Девушка, 1909 год (Всемирный Год Войны), хикки.
